### PR TITLE
Added GCR support to credential addon

### PR DESCRIPTION
**Pull request by aaron-prindle**

### CODE REVIEW

**Comment by stevesloka** [comment]
Hey @aaron-prindle I'm getting build errors trying to build: 

```
~/g/s/g/u/awsecr-creds ❯❯❯ make binary                                                                                                                                                                                            gcr ◼
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -installsuffix cgo --ldflags '-w' ./aws_credentials.go
# github.com/upmc-enterprises/awsecr-creds/vendor/k8s.io/kubernetes/pkg/apis/meta/v1
vendor/k8s.io/kubernetes/pkg/apis/meta/v1/helpers.go:38: cannot use []string literal (type []string) as type sets.String in argument to labels.NewRequirement
vendor/k8s.io/kubernetes/pkg/apis/meta/v1/helpers.go:58: cannot use append(([]string)(nil), expr.Values...) (type []string) as type sets.String in argument to labels.NewRequirement
# github.com/upmc-enterprises/awsecr-creds/vendor/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1/zz_generated.defaults.go:31: scheme.AddTypeDefaultingFunc undefined (type *runtime.Scheme has no field or method AddTypeDefaultingFunc)
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1/zz_generated.defaults.go:32: scheme.AddTypeDefaultingFunc undefined (type *runtime.Scheme has no field or method AddTypeDefaultingFunc)
vendor/k8s.io/kubernetes/pkg/apis/componentconfig/v1alpha1/zz_generated.defaults.go:33: scheme.AddTypeDefaultingFunc undefined (type *runtime.Scheme has no field or method AddTypeDefaultingFunc)
make: *** [binary] Error 2
```

**Comment by aaron-prindle** [comment]
I am not sure what the issue could be, when I clone the repository new and checkout my branch it seems to build for me:
```
aprindle@aprindle:~/go-test/src/github/upmc-enterprises$ git clone https://github.com/aaron-prindle/awsecr-creds
Cloning into 'awsecr-creds'...
remote: Counting objects: 2111, done.
remote: Compressing objects: 100% (32/32), done.
remote: Total 2111 (delta 3), reused 0 (delta 0), pack-reused 2077
Receiving objects: 100% (2111/2111), 3.67 MiB | 0 bytes/s, done.
Resolving deltas: 100% (538/538), done.
aprindle@aprindle:~/go-test/src/github/upmc-enterprises$ cd awsecr-creds/
aprindle@aprindle:~/go-test/src/github/upmc-enterprises/awsecr-creds$ git checkout 
add-gcr             master              origin/HEAD         origin/version1.2   
HEAD                origin/add-gcr      origin/master       version1.2          
aprindle@aprindle:~/go-test/src/github/upmc-enterprises/awsecr-creds$ git checkout add-gcr 
Branch add-gcr set up to track remote branch add-gcr from origin.
Switched to a new branch 'add-gcr'
aprindle@aprindle:~/go-test/src/github/upmc-enterprises/awsecr-creds$ make clean
rm -f awsecr-creds
aprindle@aprindle:~/go-test/src/github/upmc-enterprises/awsecr-creds$ make binary
GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -a -installsuffix cgo --ldflags '-w' ./aws_credentials.go
aprindle@aprindle:~/go-test/src/github/upmc-enterprises/awsecr-creds$ 
```

**Comment by aaron-prindle** [comment]
Please let me know how I should setup my environment to replicate yours, I am currently confused as to what dependencies I may not have vendored properly as `make binary` builds in my setup.  Thanks.

**Comment by stevesloka** [comment]
I'm not sure what's up, I did your same flow and everything worked. Must of been how I checked out the PR through my repo. I can build now, let me finalize a look and I can merge this in.

**Comment by stevesloka** [comment]
@aaron-prindle I think it was my mac, building on my linux box worked just fine. 

One quick question, how does google auth happen? Like what credentials need to exist to get a token for me? For AWS we pass access-key and secret, what does google need to make this work? (I was working to update the readme).

**Comment by aaron-prindle** [comment]
ref: #25

**Pull request merged**
